os:
  - linux
  - windows
  - osx

sudo: false

language: node_js

node_js:
  - "8"
  - "10"
  - "11"
  - "node"

install:
  - npm install

# note, the original master branch using nan did not have a travis
# job on windows and when unit tested was found to have breaking
# tests. If these were fixed existing work arounds would be broken
# on windows.
script:
  - node --version
  - npm --version
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then npm test ; fi
