os:
  - linux
  - osx

sudo: false

language: node_js

node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"

install:
  - PATH="`npm bin`:`npm bin -g`:$PATH"
  - npm install

script:
  - node --version
  - npm --version
  - npm test
