os:
  - linux
  - osx
  - windows

sudo: false

language: node_js

node_js:
  - "10"

install:
  - PATH="`npm bin`:`npm bin -g`:$PATH"
  - npm install

script:
  - node --version
  - npm --version
  - npm test
